name: mcRoyale
main: com.mileses.mcroyale.McRoyale
version: 0.01
author: nick
database: true
softdepend: [CompassRadar]
commands:
  royale:
    description: Top level hunger games command
    usage: /<command> help
    permission: McRoyale.royale
    permission-message: You don't have <permission>